# Generated by Django 3.1.2 on 2020-10-30 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('descript', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerchoice',
            name='page',
        ),
    ]
